---
permalink: performance-checker/concept_what_expected_range_of_performance_is.html 
sidebar: sidebar 
keywords: expected, range, performance, latency, forecast, formed 
summary: 지연 시간 예측은 특정 시간에 있을 것으로 예상되는 상한 및 하한 성능 값을 예측한 것입니다. 워크로드 지연 시간의 경우 상한값이 성능 임계값을 구성합니다. 실제 값이 성능 임계값을 넘어가면 Unified Manager가 동적 성능 이벤트를 트리거합니다. 
---
= 예상되는 성능 범위는 얼마입니까
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
지연 시간 예측은 특정 시간에 있을 것으로 예상되는 상한 및 하한 성능 값을 예측한 것입니다. 워크로드 지연 시간의 경우 상한값이 성능 임계값을 구성합니다. 실제 값이 성능 임계값을 넘어가면 Unified Manager가 동적 성능 이벤트를 트리거합니다.

예를 들어, 오전 9시부터 오후 5시까지 정규 업무 시간 동안 대부분의 직원은 오전 9시부터 오전 10시 30분 사이에 이메일을 확인할 수 있습니다. 이메일 서버에 대한 수요가 증가하면 이 시간 동안 백엔드 스토리지의 작업 부하 작업이 증가하게 됩니다. 직원들은 이메일 클라이언트에서 느린 응답 시간을 알아차릴 수 있습니다.

오후 12시부터 오후 1시까지 점심시간 및 오후 5시 이후 업무일 종료 시에는 대부분의 직원이 컴퓨터를 사용하지 않을 가능성이 높습니다. 일반적으로 이메일 서버에 대한 수요가 감소하므로 백엔드 스토리지에 대한 요구도 감소합니다. 또는 오후 5시 이후에 시작되어 백엔드 스토리지에서 작업을 증가시키는 스토리지 백업 또는 바이러스 검사 등의 예약된 작업 부하 작업이 있을 수 있습니다.

워크로드 활동의 증가 및 감소는 몇 일 동안 작업의 예상 범위(지연 시간 예측)를 결정합니다. 워크로드의 범위는 상한 및 하단으로 결정됩니다. 개체의 실제 워크로드 활동이 상한 또는 하위의 경계를 벗어나 일정 기간 동안 경계 외부에 있는 경우, 개체가 초과 사용 또는 과소사용됨을 나타낼 수 있습니다.



== 지연 시간 예측 구성 방법

Unified Manager에서 분석을 시작하기 전에, 그리고 GUI에 I/O 응답 시간에 대한 지연 시간 예측을 표시할 수 있으려면 최소 3일간의 워크로드 활동을 수집해야 합니다. 필요한 최소 데이터 수집은 워크로드 활동에서 발생하는 모든 변경 사항을 고려하지 않습니다. Unified Manager는 처음 3일간의 활동을 수집한 후 오전 12시마다 지연 시간 예측을 조정하여 워크로드 활동 변경사항을 반영하고 보다 정확한 동적 성능 임계값을 설정합니다.

[NOTE]
====
DST(일광 절약 시간)는 시스템 시간을 변경하여 모니터링되는 워크로드의 성능 통계에 대한 지연 시간 예측을 변경합니다. Unified Manager가 즉시 지연 시간 예측을 수정하기 시작하므로, 완료하는 데 약 15일이 소요됩니다. 이때 Unified Manager를 계속 사용할 수 있지만, Unified Manager에서는 지연 시간 예측을 사용하여 동적 이벤트를 감지하므로 일부 이벤트는 정확하지 않을 수 있습니다. 시간 변경 전에 감지된 이벤트는 영향을 받지 않습니다.

====