---
permalink: install-linux/task_selinux_requirements_for_mounting_opt_netapp.html 
sidebar: sidebar 
keywords: unified manager, selinux requirements, mounting, nfs, cifs, share 
summary: NAS 또는 SAN 장치에 /opt/NetApp 또는 /opt/NetApp/데이터를 마운트하고 SELinux를 사용하도록 설정한 경우 다음 사항을 고려해야 합니다. 
---
= NFS 및 CIFS 공유에 대한 SELinux 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
 `/opt/netapp/data`NAS 또는 SAN 디바이스에 또는 를 마운트하려는 경우 SELinux를 사용하도록 설정한 경우 `/opt/netapp` 몇 가지 고려 사항을 고려해야 합니다.

루트 파일 시스템 이외의 위치에서 또는 `/opt/netapp/data` 마운트하려는 경우, 사용자 환경에서 SELinux를 사용하도록 설정한 경우 `/opt/netapp` 마운트된 디렉토리에 대한 올바른 컨텍스트를 설정해야 합니다. 사용자 환경의 해당 시나리오에 대해 올바른 SELinux 컨텍스트를 설정하고 확인하려면 다음 단계를 수행하십시오.



== 가 마운트될 때 SELinux 컨텍스트를 구성합니다 `/opt/netapp/data`

시스템에 마운트되어 있고 SELinux가 로 설정되어 있는 `Enforcing` 경우 `/opt/netapp/data` SELinux 컨텍스트 유형이 `/opt/netapp/data` 데이터베이스 파일 위치의 기본 컨텍스트 요소인 로 설정되어 `mysqld_db_t` 있는지 확인합니다.

. 다음 명령을 실행하여 컨텍스트를 확인합니다.
+
`ls -dZ /opt/netapp/data`

+
샘플 출력:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:default_t:s0 /opt/netapp/data
----
+

NOTE: 이 출력에서 컨텍스트는 `default_t` 입니다. 이 컨텍스트를 로 `mysqld_db_t`변경해야 합니다.

. 다음 단계를 수행하여 탑재 방법에 따라 컨텍스트를 `/opt/netapp/data` 설정합니다.
+
.. 다음 명령을 실행하여 컨텍스트를 로 `mysqld_db_t`설정합니다.
`semanage fcontext -a -t mysqld_db_t "/opt/netapp/data"
`restorecon -R -v /opt/netapp/data`
.. 에서 `/etc/fstab` 를 구성한 경우 `/opt/netapp/data` 파일을 편집해야 `/etc/fstab` 합니다. 마운트 옵션의 경우 `/opt/netapp/data/` MySQL 레이블을 다음과 같이 추가합니다.
+
`context=system_u:object_r:mysqld_db_t:s0`

.. 컨텍스트를 활성화하기 위해 마운트 해제 및 다시 마운트합니다. `/opt/netapp/data/`
.. 직접 NFS 마운트가 있는 경우 다음 명령을 실행하여 컨텍스트를 로 설정합니다 `mysqld_db_t`.
+
`mount <nfsshare>:/<mountpoint> /opt/netapp/data -o context=system_u:object_r:mysqld_db_t:s0`



. 컨텍스트가 올바르게 설정되었는지 확인합니다.


`ls -dZ /opt/netapp/data/`

샘플 출력:

[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/data/
----


== 가 마운트되어 있으며 별도로 마운트되는 `/opt/netapp/data/` 경우 SELinux 컨텍스트를 구성합니다 `/opt/netapp`

이 시나리오에서는 먼저 이전 섹션에서 설명한 대로 의 컨텍스트를 `/opt/netapp/data/` 설정해야 합니다. 에 대한 올바른 컨텍스트를 설정한 후 `/opt/netapp/data/` 상위 디렉토리에 `/opt/netapp` SELinux 컨텍스트가 로 설정되어 `file_t` 있지 않은지 확인합니다.

.단계
. 다음 명령을 실행하여 컨텍스트를 확인합니다.
+
`ls -dZ /opt/netapp`

+
샘플 출력:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:file_t:s0 /opt/netapp
----
+
이 출력에서는 컨텍스트가 `file_t` 변경되어야 합니다. 다음 명령은 컨텍스트를 로 `usr_t`설정합니다. 컨텍스트를 보안 요구 사항을 기반으로 하지 않는 값으로 설정할 수 `file_t` 있습니다.

. 탑재된 방법에 따라 컨텍스트를 설정하려면 다음 단계를 `/opt/netapp` 수행하십시오.
+
.. 다음 명령을 실행하여 컨텍스트를 설정합니다.




[listing]
----
semanage fcontext -a -t usr_t "/opt/netapp"
restorecon -v /opt/netapp
----
. 에서 `/etc/fstab` 를 구성한 경우 `/opt/netapp` 파일을 편집해야 `/etc/fstab` 합니다. 마운트 옵션의 경우 `/opt/netapp` MySQL 레이블을 다음과 같이 추가합니다.
+
`context=system_u:object_r:usr_t:s0`

. 마운트 해제한 후 다시 마운트하여 `/opt/netapp` 컨텍스트를 설정합니다.
. 직접 NFS 마운트가 있는 경우 다음 명령을 실행하여 컨텍스트를 설정합니다.
+
`mount <nfsshare>:/<mountpoint> /opt/netapp -o context=system_u:object_r:usr_t:s0`

+
.. 컨텍스트가 올바르게 설정되었는지 확인합니다.
+
`ls -dZ /opt/netapp`

+
샘플 출력입니다





[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:usr_t:s0 /opt/netapp
----


== 가 마운트되어 있으며 별도로 마운트되지 않은 `/opt/netapp/data/` 경우 SELinux 컨텍스트를 구성합니다 `/opt/netapp`

시스템에 마운트되어 있고 SELinux가 로 설정되어 있는 `Enforcing` 경우  `/opt/netapp`SELinux 컨텍스트 유형이 `/opt/netapp` 데이터베이스 파일 위치의 기본 컨텍스트 요소인 로 설정되어 `mysqld_db_t` 있는지 확인합니다.

.단계
. 다음 명령을 실행하여 컨텍스트를 확인합니다.
+
`ls -dZ /opt/netapp`

+
샘플 출력:

+
[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:default_t:s0 /opt/netapp
----
+

NOTE: 이 출력에서 컨텍스트는 `default_t` 입니다. 이 컨텍스트를 로 `mysqld_db_t`변경해야 합니다.

. 탑재된 방법에 따라 컨텍스트를 설정하려면 다음 단계를 `/opt/netapp` 수행하십시오.
+
.. 다음 명령을 실행하여 컨텍스트를 로 `mysqld_db_t`설정합니다.
`semanage fcontext -a -t mysqld_db_t "/opt/netapp"
`restorecon -R -v /opt/netapp`
.. 에서 `/etc/fstab` 를 구성한 경우 `/etc/fstab` 파일을 편집합니다 `/opt/netapp`. 마운트 옵션의 경우 `/opt/netapp/` MySQL 레이블을 다음과 같이 추가합니다.
`context=system_u:object_r:mysqld_db_t:s0`
.. 마운트 해제한 후 다시 마운트하여 `/opt/netapp/` 컨텍스트를 설정합니다.
.. 직접 NFS 마운트가 있는 경우 다음 명령을 실행하여 컨텍스트를 로 설정합니다 `mysqld_db_t`.
`mount <nfsshare>:/<mountpoint> /opt/netapp -o context=system_u:object_r:mysqld_db_t:s0`


. 컨텍스트가 올바르게 설정되었는지 확인합니다.


`ls -dZ /opt/netapp/`

샘플 출력:

[listing]
----
drwxr-xr-x. mysql root unconfined_u:object_r:mysqld_db_t:s0 /opt/netapp/
----
'''